version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: Max.12345678
      POSTGRES_DB: colectiva
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: neo4j-db
    restart: always
    ports:
      - "7474:7474" # Interfaz web de Neo4j
      - "7687:7687" # Bolt (conexión desde el código)
    environment:
      NEO4J_AUTH: neo4j/Max.42684627 # Formato: usuario/contraseña
    volumes:
      - neo4j-data:/data

volumes:
  postgres-data:
  neo4j-data:
